# Generated by Django 3.1.6 on 2021-06-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='time',
            field=models.CharField(max_length=6),
        ),
    ]
