# Generated by Django 3.1.6 on 2021-06-21 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20210621_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='cell',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 21, 15, 43, 39, 326428)),
        ),
    ]
