# Generated by Django 3.1.6 on 2021-06-25 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20210621_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='media/example/images')),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='cell',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
