# Generated by Django 3.1.6 on 2021-06-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20210625_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/example/images'),
        ),
    ]
